### ISSUE TITLE
Repo structure

### ISSUE THREAD

**Issue by JakubRakus** [RaspdasTeam/raspdas#2]
I'd like to propose a structure of our repository. I think that every "sub-project" should have its own folder in main directory of repo, i.e:

```
raspdas
| - Server
   | - FW_System
   | - SW_DataBase
   | - SW_WebApp
   .
   .
   .
   | - HW_ShieldForOtherIf
| - SensorWiFi
   | - HW_ESP8266BasedIncredibleDevice
   | - FW_AmazingWiFiFirmware
| - SensorLAN
| - SensorUART
.
.
.
| - SensorOtherIf
```

Also, as @artur-ba proposed, there should be minimum two branches: one **master** with official version, and one **devel** for version under actual development.

**Comment by myma84** [comment]
Quite good idea. I would go further and make it a little more complex. For example:

```
raspdas
|
|--sensors
|       |
|       |-- WiFiSensor
|       |        |
|       |        |-- hardware
|       |        |-- firmware
|       |        |-- tools (?)
|       |
|       |-- LanSensor
|       |-- SerialSensor
|       |-- OtherIfSensor
|
|--sdp
|    |
|    |--NetSdp
|    |--1wSdp
|    |--SerialSdp
|    |--OtherIfSdp
|
|--wc
|   |
|   |-- index.php
|   |-- (other files)
|
|--db
    |
    |-- (sql scripts)

```

As far as the devel branch is concern, I have already done it.

**Comment by JakubRakus** [comment]
My first proposal was based more on physical than logical structure - You know, I am a hardware guy so I feel more comfortable with "real" things ;) - but this directory tree looks very good and I have to admit that better corresponds to logical structure of the whole system, as presented in #1. I think we may start using it. Everyone agree?

**Comment by myma84** [comment]
Another idea is to create several repos - one for every component of the system.

What do the team think about it ?

**Comment by myma84** [comment]
> Another idea is to create several repos - one for every component of the system.
> What do the team think about it ?

Due to the fact that there is no objections :) we take this idea and I close this issue.
